#!/usr/bin/env lua

local r = require'redis'
local client = r:connect()
if not client:ping() then return end

local command = arg[1] or ""

if command:lower() == "list" then
	local whitelist = client:lrange("rss:whitelist", 0, -1)
	for i, v in next, whitelist do
		print(i, v)
	end
elseif command:lower() == "add" then
	client:rpush("rss:whitelist", arg[2])
	print(arg[2] .. " has been added")
elseif(command:lower() == "format") then
	local magic = {
		["%."] = "%%%.",
		["%-"] = "%%-",
		["%+"] = "%%+",
		["%*"] = "%%*",
		["%?"] = "%%?",
		["%["] = "%%[",
		["%]"] = "%%]",
		["%("] = "%%(",
		["%)"] = "%%)",
		["%^"] = "%%^",
		["%$"] = "%%$",
		["\226\128\139"] = "",
	}
	local btrss = {
		[" "] = "_",
		["<ep>"] = "(.-)",
		["<drop>"] = ".-",
		["<ext>"] = "%[%%a%%d%]%+%$",
	}

	local input = arg[2]
	if(input ~= "") then
		for k, v in pairs(magic) do
			input = input:gsub(k, v)
		end

		for k, v in pairs(btrss) do
			input = input:gsub(k, v)
		end
	else
		input = "No input."
	end

	print(input)
end

client:quit()
